name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
          - { icon: '🟨', sys: ucrt64  } # Experimental!
          - { icon: '🟧', sys: clang64 } # Experimental!

    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}

    defaults:
      run:
        shell: msys2 {0}

    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
          zlib
          brotli

    - name: cd_lib
      run: cd lib
      
    - name: make_lib
      run: make

    - name: cd_test
      run: cd ../test
      
    - name: make_cd_test
      run: make

