name: Static library build

on:
  push:
    branches: ['main']
    paths: ['lambda.hpp', 'lambda_version.hpp', 'lambda_private.hpp']
  pull_request:
    branches: ['main']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build
        run: make libstatic
