name: Full library build

on:
  push:
    branches: ['main']
    paths: ['lambda.hpp', 'lambda_version.hpp', 'lambda_private.hpp']
  pull_request:
    branches: ['main']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Git Sumbodule Update
        run: git submodule update

      - name: build
        run: make test_build
